version: '3.8'

services:
  music-app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./music_app:/music_app
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=admin
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: sh -c "celery -A music-app.celery worker --loglevel=info"
    volumes:
      - ./music_app:/music_app
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=admin
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

   


  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./mucis_app:/mucis_app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

      